# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cefa5ab1b1ae0d0746535a78e6fea4d3222e7419c3e202e2dbb6f917e15e8628c56c59ae8e64ddd97dd07fd29d09df8974849f2d3dc0712819f6b2ce275d1f16

test:
  secret_key_base: e18f624337e703dcff5fa8a10e05ab21259f6cc187ae55c18e0d3e5becf096d9832fa378d04d9661aef8c60af134a1166bff3377c994194ef51d2bfc87b66272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
secret_key_base: 10abfaf5ea18c7427378bd01ac07283f62ff14e5550fd29823b0ad5c48a40eca7709780f680bfa6b52b64215d4f624056c2193368ebb683733ed2590df1cbe49
#secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

